// Code generated by protoc-gen-go.
// source: http_record.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	http_record.proto

It has these top-level messages:
	HTTPMessage
	HTTPHeader
	RequestResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestResponse_Scheme int32

const (
	RequestResponse_HTTP  RequestResponse_Scheme = 1
	RequestResponse_HTTPS RequestResponse_Scheme = 2
)

var RequestResponse_Scheme_name = map[int32]string{
	1: "HTTP",
	2: "HTTPS",
}
var RequestResponse_Scheme_value = map[string]int32{
	"HTTP":  1,
	"HTTPS": 2,
}

func (x RequestResponse_Scheme) Enum() *RequestResponse_Scheme {
	p := new(RequestResponse_Scheme)
	*p = x
	return p
}
func (x RequestResponse_Scheme) String() string {
	return proto1.EnumName(RequestResponse_Scheme_name, int32(x))
}
func (x *RequestResponse_Scheme) UnmarshalJSON(data []byte) error {
	value, err := proto1.UnmarshalJSONEnum(RequestResponse_Scheme_value, data, "RequestResponse_Scheme")
	if err != nil {
		return err
	}
	*x = RequestResponse_Scheme(value)
	return nil
}
func (RequestResponse_Scheme) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type HTTPMessage struct {
	FirstLine        []byte        `protobuf:"bytes,1,opt,name=first_line,json=firstLine" json:"first_line,omitempty"`
	Header           []*HTTPHeader `protobuf:"bytes,2,rep,name=header" json:"header,omitempty"`
	Body             []byte        `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *HTTPMessage) Reset()                    { *m = HTTPMessage{} }
func (m *HTTPMessage) String() string            { return proto1.CompactTextString(m) }
func (*HTTPMessage) ProtoMessage()               {}
func (*HTTPMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HTTPMessage) GetFirstLine() []byte {
	if m != nil {
		return m.FirstLine
	}
	return nil
}

func (m *HTTPMessage) GetHeader() []*HTTPHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *HTTPMessage) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type HTTPHeader struct {
	Key              []byte `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            []byte `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HTTPHeader) Reset()                    { *m = HTTPHeader{} }
func (m *HTTPHeader) String() string            { return proto1.CompactTextString(m) }
func (*HTTPHeader) ProtoMessage()               {}
func (*HTTPHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HTTPHeader) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *HTTPHeader) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type RequestResponse struct {
	Ip               *string                 `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port             *uint32                 `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Scheme           *RequestResponse_Scheme `protobuf:"varint,3,opt,name=scheme,enum=MahimahiProtobufs.RequestResponse_Scheme" json:"scheme,omitempty"`
	Request          *HTTPMessage            `protobuf:"bytes,4,opt,name=request" json:"request,omitempty"`
	Response         *HTTPMessage            `protobuf:"bytes,5,opt,name=response" json:"response,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *RequestResponse) Reset()                    { *m = RequestResponse{} }
func (m *RequestResponse) String() string            { return proto1.CompactTextString(m) }
func (*RequestResponse) ProtoMessage()               {}
func (*RequestResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestResponse) GetIp() string {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return ""
}

func (m *RequestResponse) GetPort() uint32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *RequestResponse) GetScheme() RequestResponse_Scheme {
	if m != nil && m.Scheme != nil {
		return *m.Scheme
	}
	return RequestResponse_HTTP
}

func (m *RequestResponse) GetRequest() *HTTPMessage {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *RequestResponse) GetResponse() *HTTPMessage {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto1.RegisterType((*HTTPMessage)(nil), "MahimahiProtobufs.HTTPMessage")
	proto1.RegisterType((*HTTPHeader)(nil), "MahimahiProtobufs.HTTPHeader")
	proto1.RegisterType((*RequestResponse)(nil), "MahimahiProtobufs.RequestResponse")
	proto1.RegisterEnum("MahimahiProtobufs.RequestResponse_Scheme", RequestResponse_Scheme_name, RequestResponse_Scheme_value)
}

func init() { proto1.RegisterFile("http_record.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x91, 0x4d, 0x4f, 0x32, 0x31,
	0x14, 0x85, 0x33, 0x85, 0xe1, 0xe3, 0xf2, 0xbe, 0x08, 0x37, 0x2e, 0xba, 0xc1, 0x90, 0x59, 0xe1,
	0x66, 0x16, 0x44, 0x13, 0xe3, 0x4e, 0x57, 0x2c, 0x24, 0x21, 0x85, 0x95, 0x1b, 0x32, 0xc0, 0xc5,
	0x69, 0x04, 0x5a, 0xdb, 0x8e, 0x86, 0x1f, 0xe1, 0x7f, 0x36, 0xed, 0x8c, 0x9a, 0xf8, 0x91, 0xb8,
	0x3b, 0xf7, 0xe6, 0x39, 0xe7, 0x9e, 0x99, 0x42, 0x3f, 0x77, 0x4e, 0x2f, 0x0d, 0xad, 0x95, 0xd9,
	0xa4, 0xda, 0x28, 0xa7, 0xb0, 0x3f, 0xcd, 0x72, 0xb9, 0xcf, 0x72, 0x39, 0xf3, 0xe3, 0xaa, 0xd8,
	0xda, 0xe4, 0x05, 0x3a, 0x93, 0xc5, 0x62, 0x36, 0x25, 0x6b, 0xb3, 0x07, 0xc2, 0x01, 0xc0, 0x56,
	0x1a, 0xeb, 0x96, 0x3b, 0x79, 0x20, 0x1e, 0x0d, 0xa3, 0xd1, 0x3f, 0xd1, 0x0e, 0x9b, 0x3b, 0x79,
	0x20, 0xbc, 0x84, 0x46, 0x4e, 0xd9, 0x86, 0x0c, 0x67, 0xc3, 0xda, 0xa8, 0x33, 0x1e, 0xa4, 0xdf,
	0x12, 0x53, 0x1f, 0x37, 0x09, 0x90, 0xa8, 0x60, 0x44, 0xa8, 0xaf, 0xd4, 0xe6, 0xc8, 0x6b, 0x21,
	0x2f, 0xe8, 0xe4, 0x02, 0xe0, 0x93, 0xc4, 0x1e, 0xd4, 0x1e, 0xe9, 0x58, 0x1d, 0xf4, 0x12, 0x4f,
	0x21, 0x7e, 0xce, 0x76, 0x05, 0x71, 0x16, 0x76, 0xe5, 0x90, 0xbc, 0x32, 0x38, 0x11, 0xf4, 0x54,
	0x90, 0x75, 0x82, 0xac, 0x56, 0x07, 0x4b, 0xd8, 0x05, 0x26, 0x75, 0xb0, 0xb6, 0x05, 0x93, 0xda,
	0x5f, 0xd3, 0xca, 0xb8, 0x60, 0xfc, 0x2f, 0x82, 0xc6, 0x1b, 0x68, 0xd8, 0x75, 0x4e, 0x7b, 0x0a,
	0x1d, 0xba, 0xe3, 0xf3, 0x1f, 0x8a, 0x7f, 0xc9, 0x4d, 0xe7, 0xc1, 0x20, 0x2a, 0x23, 0x5e, 0x41,
	0xd3, 0x94, 0x04, 0xaf, 0x0f, 0xa3, 0x51, 0x67, 0x7c, 0xf6, 0xcb, 0xc7, 0x57, 0xff, 0x52, 0xbc,
	0xe3, 0x78, 0x0d, 0x2d, 0x53, 0x85, 0xf2, 0xf8, 0x4f, 0xd6, 0x0f, 0x3e, 0x19, 0x40, 0xa3, 0xec,
	0x81, 0x2d, 0xa8, 0x7b, 0xa4, 0x17, 0x61, 0x1b, 0x62, 0xaf, 0xe6, 0x3d, 0x76, 0xdb, 0xbc, 0x8f,
	0xc3, 0xd3, 0xbe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xc7, 0xbe, 0x57, 0xee, 0x01, 0x00, 0x00,
}
